sentence = input("Enter a sentence: ")
sentence_with_underscores = sentence.replace(' ', '_')
words = sentence.split()
print("Sentence with underscores:", sentence_with_underscores)
print("Words from the sentence:", words)